include:
  - template: Terraform/Base.latest.gitlab-ci.yml
  - template: Jobs/SAST-IaC.latest.gitlab-ci.yml

kics-iac-sast:
  cache: []

variables:
  IGNORE_TF_DEPRECATION_WARNING: "true"

stages:
  - validate
  - test
  - build
  - deploy
  - cleanup

fmt:
  extends: .terraform:fmt

validate:
  extends: .terraform:validate

build:
  extends: .terraform:build
  variables:
    TF_VAR_MY_IP: ${GITLAB_MY_IP}

deploy:
  extends: .terraform:deploy
  dependencies:
    - build
  environment:
    name: $TF_STATE_NAME
  rules:
    - when: manual
  allow_failure: true

cleanup:
  extends: .terraform:destroy
  needs: ['deploy']
  environment:
    name: $TF_STATE_NAME
  variables:
    TF_VAR_MY_IP: ${GITLAB_MY_IP}
  rules:
    - when: manual
